   0.000             NaN              NaN
   0.100             NaN              NaN
   0.200             NaN              NaN
   0.300             NaN              NaN
   0.400             NaN              NaN
   0.500             NaN              NaN
   0.600             NaN              NaN
   0.700             NaN              NaN
   0.800             NaN              NaN
   0.900             NaN              NaN
   1.000             NaN              NaN
   1.100             NaN              NaN
   1.200             NaN              NaN
   1.300             NaN              NaN
   1.400             NaN              NaN
   1.500             NaN              NaN
   1.600             NaN              NaN
   1.700             NaN              NaN
   1.800             NaN              NaN
   1.900             NaN              NaN
   2.000             NaN              NaN
