name: CI


on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
  
  
jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        # os: [ubuntu-22.04,macos-latest]
        os: [ubuntu-22.04]
        python-version: [3.11]
        toolchain:
          # - {compiler: intel, version: '2023.2'}
          - {compiler: intel-classic, version: '2021.10'}
        # exclude:
          # - os: macos-latest
          # - toolchain: {compiler: intel, version: '2023.2'}
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4  
      with:
        submodules: 'recursive'
    # - name: get submodule
      # uses: actions/checkout@v4
      # with: 
        # token: ${{ secrets.GH_PAT }}
        # repository: MCEND-hub/MCEND-library
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: setup fortran and mkl
      uses: ssciwr/setup-fortran@v0.1
      id: setup-fortran
      with:
        compiler: ${{ matrix.toolchain.compiler }}
        version: ${{ matrix.toolchain.version }}
        install_mkl: "true"
    - name: install fftw3
      run: |
        sudo apt-get install libfftw3-dev
  #  - name: Install python dependencies for the tests
#      run: |
#        python -m pip install uv
    # - name: set basis library env var
      # run: |
        # cd MCEND-library/basis_library/
        # echo "MCEND_BASIS_LIBRARY=$(pwd)" >> $GITHUB_ENV
    - name: compile MCEND - classic intel
      run: |
        make classic
    # - name: Run tests
      # run: |
        # cd tests
        # ./test.sh
      