name: CI


on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
  
  
jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest]
        # os: [ubuntu-22.04,macos-latest]
        # os: [ubuntu-22.04]
        python-version: [3.11]
        toolchain:
          # - {compiler: intel, version: '2023.2'}
          - {compiler: intel-classic, version: '2021.9'}
        # exclude:
          # - os: macos-latest
          # - toolchain: {compiler: intel, version: '2023.2'}
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4  
      with:
        submodules: 'recursive'
    # - name: get submodule
      # uses: actions/checkout@v4
      # with: 
        # token: ${{ secrets.GH_PAT }}
        # repository: MCEND-hub/MCEND-library
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: setup fortran and mkl
      uses: ssciwr/setup-fortran@v0.1
      id: setup-fortran
      with:
        compiler: ${{ matrix.toolchain.compiler }}
        version: ${{ matrix.toolchain.version }}
        install_mkl: "true"
    - name: install fftw3 linux
      if: runner.os == 'Linux'
      run: |
        sudo apt-get install libfftw3-dev
    - name: install fftw3 mac
      if: runner.os == 'macOS'
      run: |
        brew install fftw
        brew --prefix fftw
        export DYLD_LIBRARY_PATH=/opt/homebrew/Cellar/fftw/3.3.10_1/lib:$DYLD_LIBRARY_PATH
        # echo "FFTWLIB=/opt/homebrew/Cellar/fftw/3.3.10_1/lib" >> $GITHUB_ENV
#    - name: Install python dependencies for the tests
#      run: |
#        python -m pip install uv
    - name: set basis library env var
      run: |
        cd MCEND-library/basis_library/
        echo "MCEND_BASIS_LIBRARY=$(pwd)" >> $GITHUB_ENV
    - name: compile MCEND - classic intel
      if: matrix.toolchain.compiler == 'intel-classic'
      run: |
        make classic
    - name: compile MCEND - ifx
      if: matrix.toolchain.compiler == 'intel'
      run: |
        make
    - name: Run tests
      run: |
        cd tests
        ./test.sh
      
