name: CI


on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
  
  
jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        # os: [ubuntu-22.04,macos-latest]
        os: [ubuntu-22.04]
        python-version: [3.11]
        toolchain:
          # - {compiler: intel, version: '2023.2'}
          - {compiler: intel-classic, version: '2021.10'}
        # exclude:
          # - os: macos-latest
          # - toolchain: {compiler: intel, version: '2023.2'}
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: setup fortran and mkl
      uses: ssciwr/setup-fortran@v0.1
      id: setup-fortran
      with:
        compiler: ${{ matrix.toolchain.compiler }}
        version: ${{ matrix.toolchain.version }}
        install_mkl: "true"
#    - name: Install python dependencies
#      run: |
#        python -m pip install uv
    - name: compile MCEND - classic intel
      run: |
        mkdir build
        make
      